moviesphere/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/',views.signup_view, name='signup'),
    path('login/',views.login_view, name='login'),
    path('logout/',views.logout_view, name='logout'),
]

moviesphere/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.movie_list, name='list'),
    path('<int:id>/',views.movie_detail, name= 'detail'),
    path('<int:id>/create-review/', views.movie_create_review, name='create-review'),
    path('<int:id>/edit-review/', views.movie_edit_review, name='edit-review'),
    path('<int:id>/delete-review/<int:review_id>/', views.movie_delete_review, name='delete-review'),
    #path('<slug:slug>/',views.movie_detail, name= 'detail'),
]

moviesphere/moviesphere/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from movies import views as movie_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('',movie_views.movie_list, name='home')
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moviesphere/accounts/models.py
from django.db import models

# Create your models here.

moviesphere/movies/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg

# Movie model
class Movie(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    director = models.CharField(max_length=30)
    actors = models.TextField()
    year = models.CharField(max_length=4)
    thumb = models.ImageField(default='default.jpg',blank=True)
    trailer_url = models.URLField(max_length=200, blank=True, null=True)

    @property
    def average_rating(self):
        avg_rating = self.reviews.aggregate(Avg('rating'))['rating__avg']
        return avg_rating if avg_rating else 0

    def __str__(self):
        return self.title

# Review model
class Review(models.Model):
    movie = models.ForeignKey(Movie, related_name='reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(choices=[(i, str(i)) for i in range(1, 6)])  # Rate 1-5
    comment = models.TextField()

    class Meta:
        unique_together = ('movie', 'user')  # Ensure one review per user per movie

    def __str__(self):
        return f'{self.user.username} review on {self.movie.title}'

moviesphere/movies/forms.py
from django import forms
from . import models

class CreateReview(forms.ModelForm):
    class Meta:
        model = models.Review
        fields =  ['comment','rating']

class EditReview(forms.ModelForm):
    class Meta:
        model = models.Review
        fields =  ['comment','rating']

moviesphere/accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('movies:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('movies:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('movies:list')

moviesphere/movies/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.db.transaction import commit
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.functional import empty
from django.http import JsonResponse

from .forms import EditReview
from .models import Movie, Review
from . import forms


def movie_list(request):
    movies = Movie.objects.all().order_by('year')
    return render(request, 'movies/movie_list.html', {'movies':movies})


def movie_detail(request, id):
   movie = Movie.objects.get(id=id)
   reviews = movie.reviews.all()
   user_review = empty
   if request.user.is_authenticated:
        user_review = movie.reviews.filter(user=request.user).first()
   rating_range = range(1, 6)
   return render(request, "movies/movie_detail.html",
        {'movie':movie,'reviews':reviews,'rating_range': rating_range, 'user_review':user_review})



@login_required(login_url="/accounts/login")
def movie_create_review(request, id):
    movie = Movie.objects.get(id=id)
    if request.user.is_authenticated:
        if movie.reviews.filter(user=request.user).first():
           return redirect('movies:detail', id=id)
    if request.method == "POST":
        form = forms.CreateReview(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.movie_id = movie.id
            instance.save()
            return JsonResponse({'success': True, 'redirect_url': reverse('movies:detail', args=[movie.id])})
    else:
        form = forms.CreateReview()
    return render(request, "movies/movie_create_review.html", {'form': form, 'movie': movie})


def get_embed_url(youtube_url):
    if "youtube.com/watch?v=" in youtube_url:
        video_id = youtube_url.split("v=")[-1]
        return f"https://www.youtube.com/embed/{video_id}"
    return youtube_url  # Return original if not a YouTube link


from django.http import JsonResponse


def movie_edit_review(request, id):
    movie = Movie.objects.get(id=id)
    review = movie.reviews.filter(user=request.user).first()
    if not review:
        return redirect('movies:detail', id=movie.id)  # Handle case where user has no review

    if request.method == 'POST':
        form = forms.EditReview(request.POST, request.FILES, instance=review)
        if form.is_valid():
            form.save()  # Save the updated review
            return JsonResponse({'success': True, 'redirect_url': reverse('movies:detail', args=[movie.id])})
    else:
        form = forms.EditReview(instance=review)

    return render(request, 'movies/movie_edit_review.html', {'form': form, 'review': review})

def movie_delete_review(request, review_id,id):
    # Ensure that the method is DELETE
    if request.method == 'DELETE':
        review = get_object_or_404(Review, id=review_id, user=request.user)
        review.delete()
        return JsonResponse({'success': True, 'redirect_url': reverse('movies:detail', args=[id])})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method.'}, status=400)

moviesphere/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="glass-container">
    <div class="content">
        <!-- Welcome text section on the left -->
        <div class="welcome-text">
            <h1>Discover, Review, and Explore the best movies from around the world.</h1>
            <p>Your gateway to an extraordinary cinematic journey begins here!</p>
        </div>

        <!-- Login form section on the right -->
        <div class="login-form-container">
            <form class="site-form" action="{% url 'accounts:login' %}" method="post">
                {% csrf_token %}

                <!-- Username Field -->
                <div class="form-group">
                    {{ form.username.label_tag }}
                    <input type="text" name="{{ form.username.name }}" value="{{ form.username.value|default_if_none:'' }}" class="form-control" placeholder="Username" required>
                    {% for error in form.username.errors %}
                        <span class="error-message">{{ error }}</span>
                    {% endfor %}
                </div>

                <!-- Password Field -->
                <div class="form-group">
                    {{ form.password.label_tag }}
                    <input type="password" name="{{ form.password.name }}" class="form-control" placeholder="Password" required>
                    {% for error in form.password.errors %}
                        <span class="error-message">{{ error }}</span>
                    {% endfor %}
                </div>

                <button type="submit" class="btn-submit-login">Sign in</button>

                <div class="signup-redirect">
                    <p>Don't have an account?
                        <a href="{% url 'accounts:signup' %}" class="btn-signup-link">Signup here</a>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

moviesphere/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
<div class="signup-wrapper">
    <!-- Background image under the form -->
    <div class="signup-image-overlay">
        <img src="{% static 'movie_signup.jpg' %}" alt="Signup for Movies" class="signup-background">
    </div>

    <!-- Signup form container -->
    <div class="signup-form-container">
        <h1 class="signup-heading">Sign up</h1>
        <p class="signup-subtitle">Join our community and stay updated with the latest releases and exclusive content!</p>
        <form class="signup-form" action="{% url 'accounts:signup' %}" method="post">
            {% csrf_token %}

            <!-- Username Field -->
            <div class="form-group">
                <input type="text" name="{{ form.username.name }}" value="{{ form.username.value|default_if_none:'' }}" class="form-control signup-input" placeholder="User Name" required>
            </div>

            <!-- Email Field -->
            <div class="form-group">
                <input type="email" name="{{ form.email.name }}" value="{{ form.email.value|default_if_none:'' }}" class="form-control signup-input" placeholder="Email" required>
            </div>

            <!-- Password Field -->
            <div class="form-group">
                <input type="password" name="{{ form.password.name }}" class="form-control signup-input" placeholder="Password" required>
            </div>

            <!-- Confirm Password Field -->
            <div class="form-group">
                <input type="password" name="{{ form.confirm_password.name }}" class="form-control signup-input" placeholder="Confirm Password" required>
            </div>

             <!-- Submit Button (Centered) -->
            <div class="signup-buttons">
                <button type="submit" class="btn-signup">Sign Up</button>
            </div>

            <!-- Already have an account? Sign in section -->
            <div class="signin-redirect">
                <p>Already have an account?
                    <a href="{% url 'accounts:login' %}" class="btn-signin-link">Sign in</a>
                </p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

moviesphere/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie Sphere</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class="wrapper">
              <!-- Navbar -->
        <nav class="navbar">
            <!-- Logo on the left -->
            <div class="logo">
                <a href="{% url 'home' %}">
                    <img src="{% static 'ms-logo.png' %}" alt="Home Logo" class="logo-image" width="50">
                </a>
            </div>

            <!-- Links on the right -->
            <div class="user-options">
                {% if user.is_authenticated %}
                    <span class="greeting">Hello <strong>{{ user.username }}</strong></span>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {%csrf_token %}
                        <button type="submit" class="logout-btn">Logout</button>
                    </form>
                {% else %}
                    <form action="{% url 'accounts:login' %}" method="get">
                        <button type="submit" class="login-btn">Login</button>
                    </form>
                    <form action="{% url 'accounts:signup' %}" method="get">
                        <button type="submit" class="signup-btn">Signup</button>
                    </form>
                {% endif %}
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

moviesphere/templates/movies/movie_create_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create a New Review</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="movie-create-review glass-container">
        <h2>Create a New Review</h2>
        <form class="site-form" id="reviewForm" action="{% url 'movies:create-review' id=movie.id %}" method="post">
            {% csrf_token %}

            <!-- Comment Field -->
            <div class="form-group">
                {{ form.comment.label_tag }}
                <textarea name="{{ form.comment.name }}" class="form-control" placeholder="Write your review here..." required rows="3">{{ form.comment.value|default_if_none:'' }}</textarea>
                {% for error in form.comment.errors %}
                    <span class="error-message">{{ error }}</span>
                {% endfor %}
            </div>

            <!-- Rating Field -->
            <div class="form-group">
                {{ form.rating.label_tag }}
                <select name="{{ form.rating.name }}" class="form-control" required>
                    {% for value, display in form.rating.field.choices %}
                        <option value="{{ value }}" {% if value == form.rating.value %}selected{% endif %}>{{ display }}</option>
                    {% endfor %}
                </select>
                {% for error in form.rating.errors %}
                    <span class="error-message">{{ error }}</span>
                {% endfor %}
            </div>

            <button type="submit" class="btn-submit-review">Submit Review</button>
        </form>
    </div>

    <script>
        document.getElementById('reviewForm').addEventListener('submit', function(e) {
            e.preventDefault();  // Prevent the default form submission

            var form = this;
            var formData = new FormData(form);

            // Send the form data via AJAX to the server
            fetch(form.action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-Requested-With': 'XMLHttpRequest',
                },
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    // Send message to the parent window with the success flag and redirect URL
                    window.parent.postMessage({ success: true, redirect_url: data.redirect_url }, "*");
                }
            });
        });
    </script>
</body>
</html>

moviesphere/templates/movies/movie_detail.html
{% extends 'base_layout.html' %}
{% block content %}
<div class ="movie-detail">
    <div class="movie-thumb">
        <img src="{{movie.thumb.url}}" width="150">
    </div>
    <div class="movie-info">
        <h4> {{movie.title}} {{movie.year}} </h4>
        <h2> by {{movie.director}} </h2>
        <p> main actors : {{movie.actors}}</p>
    </div>
    <div class="movie-desc">
        <p> {{movie.description}}</p>
    </div>
</div>

 <!-- Add this modal structure inside your movie_detail template -->
<div id="reviewModal" class="movie-detail-modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <iframe id="reviewFrame" class="review-iframe" src="" frameborder="0"></iframe>
    </div>
</div>
<div id="editReviewModal" class="movie-detail-modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <iframe id="editReviewFrame" class="review-iframe" src="" frameborder="0" style="width: 100%;height: 600px;
        border: none;padding: 0;margin: 0;"></iframe>
    </div>
</div>

<div class="review-container">
    <h2 class="mb-4">Movie Reviews</h2>
     <!-- Button to create a review -->
    <div style="text-align: left; margin-bottom: 20px;">
        {% if user.is_authenticated %}
            {% if user_review %}
                <!-- If the user is logged in and has already submitted a review, show the "Edit Review" button -->
                <a href="javascript:void(0)" class="btn btn-secondary" onclick="openReviewModal('{% url 'movies:edit-review' movie.id %}')">Edit Review</a>
                 <!-- Delete Review Button -->
                <a href="javascript:void(0)" class="btn btn-danger" onclick="confirmDeleteReview('{{ user_review.id }}','{{movie.id}}')">Delete Review</a>
            {% else %}
                <!-- If the user is logged in but did not review, show the "Add Review" button -->
                <a href="javascript:void(0)" class="btn btn-primary" onclick="openReviewModal('{% url 'movies:create-review' movie.id %}')">Add Review</a>
            {% endif %}
        {% else %}
            <!-- If the user is not logged in, show a prompt to add a review -->
            <a href="javascript:void(0)" class="btn btn-primary" onclick="openReviewModal('{% url 'movies:create-review' movie.id %}')">Add Review</a>
        {% endif %}
    </div>

    {% for review in movie.reviews.all %}
    <div class="review-box">
        <!-- User Name -->
        <div class="user-name">{{ review.user.username }}</div>

         <!-- Star Rating -->
        <div class="rating">
            {% for i in rating_range %}
                {% if i <= review.rating %}
                    <span>★</span>  <!-- Solid star for ratings <= review.rating -->
                {% else %}
                    <span>☆</span>  <!-- Empty star for ratings > review.rating -->
                {% endif %}
            {% endfor %}
        </div>

        <!-- Comment -->
        <div class="comment">{{ review.comment }}</div>
    </div>
    {% empty %}
    <p>No reviews yet.</p>
    {% endfor %}
</div>

<!-- Add some CSS for the modal -->
<style>
.modal {
    display: none;
    position: fixed;
    z-index: 1;
    padding-top: 100px;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0,0,0,0.4);
}
.modal-content {
    margin: auto;
    padding: 20px;
    width: 80%;
    background-color: white;
}
.close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}
.close:hover,
.close:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
}
</style>

<script>
// Get the modal element for create review
var modal = document.getElementById("reviewModal");
// Get the modal element for edit review
var editReviewModal = document.getElementById("editReviewModal");


// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// Function to open the modal and load the URL in the iframe
function openReviewModal(url) {
    reviewFrame.src = url;
    modal.style.display = "block";

    // Listen for message from the iframe (for redirect handling)
    window.addEventListener('message', function(event) {
        if (event.data.success) {
            // Close the modal
            modal.style.display = "none";
            // Redirect the parent window to the movie detail page
            window.location.href = event.data.redirect_url;
        }
    });
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
    reviewFrame.src = ""; // Clear the iframe src to stop loading the page
}


// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
        reviewFrame.src = ""; // Clear the iframe src
    }
}

function confirmDeleteReview(reviewId,movieId) {
    if (confirm("Are you sure you want to delete this review?")) {
        fetch(`/movies/${movieId}/delete-review/${reviewId}/`, {
        method: 'DELETE',
        headers: {
            'X-Requested-With': 'XMLHttpRequest',
            'X-CSRFToken': '{{ csrf_token }}' // Ensure CSRF token is available
        }
        })
        .then(response => response.json())
        .then(data => {
            console.log(data); // Log the response for debugging
            if (data.success) {
                window.location.href = window.location.href; // Reload the current page
            } else {
                alert("Error: " + (data.error || "There was an error deleting the review."));
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert("There was an error deleting the review.");
        });
    }
}
</script>
{% endblock %}

moviesphere/templates/movies/movie_edit_review.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Edit Review</title>
    </head>
    <body>
        <h2>Edit Review for {{ review.movie.title }}</h2>

        <form method="post" id="reviewForm" action="{% url 'movies:edit-review' review.movie.id %}">
            {% csrf_token %}
            {{ form.as_p }}  <!-- Renders the form fields -->
            <button type="submit" class="btn btn-primary">Update Review</button>
        </form>


        <a href="{% url 'movies:detail' review.movie.id %}">Cancel</a>

        <script>
        document.getElementById('reviewForm').addEventListener('submit', function(e) {
            e.preventDefault();  // Prevent the default form submission

            var form = this;
            var formData = new FormData(form);

            // Send the form data via AJAX to the server
            fetch(form.action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-Requested-With': 'XMLHttpRequest',
                },
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    // Send message to the parent window with the success flag and redirect URL
                    window.parent.postMessage({ success: true, redirect_url: data.redirect_url }, "*");
                }
            });
        });
        </script>
    </body>
</html>

moviesphere/templates/movies/movie_list.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="movies-container">
    <div class="movies-grid">
        {% for movie in movies %}
        <div class="movie">
            <p>* {{movie.average_rating}}</p>
            <a href="{% url 'movies:detail' id=movie.id %}">
                <img src="{{movie.thumb.url}}" alt="{{movie.title}}" class="movie-thumb">
            </a>
            <h3>{{ movie.title }}</h3>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}